config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "offers#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  # Afficher une offer
  get "offers", to: "offers#index"
  # Routes user pour faire réservation
  get "bookings/:id/payment/new", to: "payment#new", as: :new_payment
  post "bookings/:id/payment", to: "payment#create"
  get "bookings/:id", to: "bookings#show"

  # Routes user pour créer modifier supprimer une offer
  get "offers/new", to: "offers#new", as: :new_offer
  post "offers", to: "offers#create"
  get "offers/:id/edit", to: "offers#edit", as: :edit_offer
  patch "offers/:id", to: "offers#update"
  delete "offers/:id", to: "offers#destroy"
  # Routes pour l'user qui va accepter ou refuser une réservation
  get "bookings/:id/edit", to: "bookings#edit", as: :edit_booking
  patch "bookings/:id", to: "bookings#update"
  # Afficher le profile
  get "profile", to: "pages#profile"
  get "offers/:id", to: "offers#show", as: :offer

  resources :offers do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: %i[create update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :offer

  validates :status, presence: true, inclusion: { in: ["pending", "accepted", "rejected"] }
  validates :date, presence: true
  validate :date_cannot_be_in_the_past

  private

  def date_cannot_be_in_the_past
    errors.add(:date, "cannot be earlier than today.") if date.present? && date < Date.today
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :bookings
  belongs_to :user
  has_one_attached :photo

  validates :name, presence: true
  validates :offer_type, presence: true, inclusion: { in: ["bakery", "gardening", "manual activities", "cooking", "culture"] }
  validates :description, presence: true, length: { minimum: 4 }
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :area, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :booking

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :status, presence: true, inclusion: { in: ["pending", "completed", "failed"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings, dependent: :destroy
  has_many :offers, dependent: :destroy
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: %i[show edit update destroy]
  before_action :authorize_booking_owner, only: %i[edit update destroy]

  def show
  end

  def index
    @bookings = current_user.bookings
  end

  def create
    @offer = Offer.find(params[:offer_id])

    # Vérifier si l'utilisateur tente de réserver sa propre offre
    if @offer.user == current_user
      redirect_to offer_path(@offer), alert: "You can't book your own offer!"
      return
    end

    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = @offer
    @booking.status = "pending"

    if @booking.save
      redirect_to offer_path(@offer), notice: "Booking made with success."
    else
      flash.now[:alert] = @booking.errors.full_messages.join(", ") # Afficher les erreurs
      render "offers/show", status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if params[:status].present? && @booking.offer.user == current_user
      @booking.update(status: params[:status])
      redirect_to profile_path, notice: "Booking #{params[:status]}."
    elsif @booking.user == current_user
      redirect_to profile_path, alert: "You cannot change the status of your own booking."
    else
      redirect_to profile_path, alert: "You are not authorized."
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other, notice: "Booking Cancelled"
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def authorize_booking_owner
    redirect_to root_path, alert: "You are not authorized." unless @booking.offer.user == current_user
  end

  def booking_params
    params.require(:booking).permit(:date, :status)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  before_action :set_offer, only: %i[update destroy edit show]
  before_action :authorize_user!, only: %i[edit update destroy]
  skip_before_action :authenticate_user!, only: %i[show index]

  def index
    @offers = Offer.all
  end

  def show; end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user

    if @offer.save
      redirect_to offer_path(@offer), notice: "Offer created successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @offer.update(offer_params)
      redirect_to offer_path(@offer), notice: "Offer updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @offer.destroy
    redirect_to offers_path, status: :see_other, notice: "Offer deleted successfully."
  end

  private

  def set_offer
    @offer = Offer.find(params[:id])
  end

  def authorize_user!
    redirect_to offers_path, alert: "You are not authorized to perform this action." unless @offer.user == current_user
  end

  def offer_params
    params.require(:offer).permit(:name, :description, :offer_type, :area, :price, :photo_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[profile]

  def profile
    @my_offers = current_user.offers.includes(:bookings)
    @my_bookings = current_user.bookings
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<h1>Modify booking</h1>

<%= simple_form_for @booking, url: booking_path(@booking), method: :patch do |f| %>
  <div>
    <%= f.input :status, collection: ["pending", "accepted", "declined"], label: "Booking status" %>
  </div>

  <div>
   <%= f.input :date, as: :date, label: "Booking date" %>
  </div>

  <div>
    <%= f.submit "Update", class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to "Cancel", booking_path(@booking), class: "btn btn-secondary" %>

app/views/bookings/show.html.erb
<h1>Booking for <%= @booking.offer.name %></h1>
<p>Date : <%= @booking.date %></p>
<p>Status : <%= @booking.status %></p>

<% if current_user == @booking.user %>
  <%= link_to "Edit", edit_booking_path(@booking), class: "btn btn-warning" %>
  <%= link_to "Cancel", booking_path(@booking), method: :delete, data: { confirm: "Cancel this booking ?" }, class: "btn btn-danger" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SeniorMentor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="background-gradient">
    <div class="container">



      <nav class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <div class="container-fluid">


          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag("logo_Senior_Mentor.png", alt: "Senior Mentor Logo") %>
          <% end %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <% if user_signed_in? %>
        <%= link_to "Log Out", destroy_user_session_path, data: { turbo_method: :delete }, class: "button-log-out" %>
      <% else %>
        <%= link_to "Log In", new_user_session_path %>
      <% end %>
              <%= link_to profile_path, class: "navbar-brand" do %>
            <%= image_tag("Mario.png", alt: "Mario", style: "border-radius: 50%; height: 60px; width: 60px") %>
          <% end %>
          </div>
        </div>
      </nav>

      <%= yield %>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    <div class= "margin-left: 30px; mb-4 footer">
    <%= image_tag("Logo_footer.png", alt: "Logo footer", style: "width: 150px") %>

    </div>
    </div>

  </body>
</html>

app/views/offers/edit.html.erb
<%= simple_form_for(@offer) do |f| %>

  <%= f.input :name %>
  <%= f.input :offer_type, collection: ["cooking", "bakery", "manual activities", "culture", "gardening"] %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :area %>
    <%= f.input :photo_url %>
    <%= f.button :submit %>
  <% end %>

app/views/offers/index.html.erb
<div class="container">
  <div class="wrap">
    <div class="search">
        <input type="text" class="searchTerm" placeholder="What are you looking for?">
        <button type="submit" class="searchButton">
          <i class="fa fa-search"></i>
      </button>
    </div>
  </div>

  <div class="button-container sticky-button">
    <%= link_to "+ Add a mentor", new_offer_path, class: "button button_purple" %>
  </div>

  <div class="mt-5">
    <div class="row">
      <% @offers.each do |offer| %>
        <div class="col-md-4 mb-4">
          <%= link_to offer_path(offer), :class => "text-decoration-none" do %>
          <div class="card">
            <% if offer.photo_url.present? %>
              <%= image_tag(offer.photo_url, style: "height: 248px; width: 248px; object-fit: cover; border-radius: 10px; margin: auto") %>
            <% end %>

            <div class="text-left mx-3">
              <h5><b><%= offer.name %></b></h5>
              <p><%= offer.offer_type %></p>
              <p><%= offer.area %></p>
              <h5><b><%= offer.price %>€</b></h5>
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>


  <div class="button-container-center">
    <button class= "button button_more">More mentors</button>
  </div>
</div>

app/views/offers/new.html.erb
<div class="background">
  <div class= "mt-4">
<%= simple_form_for(@offer) do |f| %>
  <%= f.input :name, placeholder: "Enter the offer name" %>
  <%= f.input :offer_type, collection: ["cooking", "bakery", "manual activities", "culture", "gardening"], prompt: "Select an offer type" %>
  <%= f.input :description, placeholder: "Describe your offer" %>
  <%= f.input :price, placeholder: "Enter the price (€)" %>
  <%= f.input :area, placeholder: "Enter the area (e.g. Paris, Lyon...)" %>
  <%= f.input :photo_url, placeholder: "Enter an image URL" %>
  <%= f.button :submit, "Create Offer" %>
<% end %>
</div>
<%= link_to "Cancel", offers_path, class: "btn btn-secondary" %>
</div>

app/views/offers/show.html.erb
<div class= "background">
  <div class= "mb-3">
<%= @offer.photo.attached? ? image_tag(@offer.photo, style: "height: 248px; width: 248px; object-fit: cover; border-radius: 10px; margin: auto") : image_tag(@offer.photo_url, style: "height: 248px; width: 248px; object-fit: cover; border-radius: 10px; margin: auto") %>
</div>
<h4><b><%= @offer.name %></b></h4>
<p><%= @offer.offer_type %></p>
<p><%= @offer.description %></p>
<p><%= @offer.area %></p>
<div class= "mb-3">
<h4><b><%= @offer.price %> €</b></h4>
</div>
<div class= "mb-3">
<%= link_to "Back to offers", offers_path %>
<%= link_to "Edit offer", edit_offer_path(@offer) %>
<%= link_to "Delete", offer_path(@offer), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
</div>
<br>
<hr>

<% if user_signed_in? %>
  <h4><b>Book this offer</b></h4>
  <%= form_with model: [@offer, @offer.bookings.new], url: offer_bookings_path(@offer), local: true do |f| %>
    <div>
      <%= f.label :date, "Choose a date :" %>
      <%= f.date_field :date, required: true %>
    </div>

    <div>
      <%= f.submit "Book", class: "button button_book" %>
    </div>
  <% end %>
<% else %>
  <p>You have to be signed in.</p>
  <%= link_to "Sign in", new_user_session_path %>
<% end %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/profile.html.erb
<div class="background">
<h1>My profile</h1>

<h3><%= current_user.email %></h3>

<h2>My bookings</h2>
<% @my_bookings.group_by(&:offer_id).each do |offer_id, bookings| %>
  <% bookings.each do |booking| %>
    <p>
      <%= link_to "#{booking.offer.name} - #{booking.offer.offer_type} - #{booking.offer.price}", offer_path(booking.offer) %>
      <span>Status: <%= booking.status.capitalize %></span>
    </p>
  <% end %>
<% end %>


<h2>Requests for my offers</h2>
<% @my_offers.each do |offer| %>
  <% offer.bookings.uniq.each do |booking| %>
    <p>
      <strong><%= booking.user.email %></strong> a réservé "<%= offer.name %>" pour le <%= booking.date %>.
      <span>Status: <%= booking.status.capitalize %></span>
    </p>
    <% if booking.status == "pending" %>
      <%= button_to "Accept", booking_path(booking, status: "accepted"), method: :patch, class: "btn btn-success" %>
      <%= button_to "Reject", booking_path(booking, status: "rejected"), method: :patch, class: "btn btn-danger" %>
    <% end %>
  <% end %>
<% end %>

<%= link_to "Back", offers_path, class:"btn btn-primary" %>
</div>